Changes added to WW3 source to permit grid-local directions in tri-polar grid closure.
- These changes allow the WW3 tripolar grid closure to use a spectral direction defined relative to the grid rather than the pole.
- This allows propagation to occur over an ice-free pole.
- Note that tripolar closure is only coded for PR1 in WW3, so this also is only coded for PR1.
- The grid-metrics can also now be read from an external file, rather than computed online using finite differences.

diff --git a/model/bin/w3_make b/model/bin/w3_make
--- a/model/bin/w3_make
+++ b/model/bin/w3_make
@@ -53,7 +53,7 @@
   fi
 
 
-# 1.c Get data from setup file - - - - - - - - - - - - - - - - - - - - - - - - 
+# 1.c Get data from setup file - - - - - - - - - - - - - - - - - - - - - - - -
 
   source $(dirname $0)/w3_setenv
   main_dir=$WWATCH3_DIR
@@ -135,9 +135,7 @@
 
 # GRID STRT BOUND OUTF OUTP TRCK GRIB GINT GX* UPRSTR LIBWW3
 #  reg_programs = non-NetCDF programs
-  reg_programs="ww3_grid" 
-  reg_programs="$reg_programs ww3_strt"
-  reg_programs="$reg_programs ww3_bound"
+  reg_programs="$ww3_bound"
   reg_programs="$reg_programs ww3_outf"
   reg_programs="$reg_programs ww3_outp"
   reg_programs="$reg_programs ww3_trck"
@@ -145,7 +143,7 @@
   reg_programs="$reg_programs ww3_gint"
   reg_programs="$reg_programs gx_outf"
   reg_programs="$reg_programs gx_outp"
-  reg_programs="$reg_programs ww3_uprstr" 
+  reg_programs="$reg_programs ww3_uprstr"
 
 # PRNC OUNF OUNP BOUNC TRNC
 # cdf_programs = NetCDF programs
@@ -154,6 +152,13 @@
   cdf_programs="$cdf_programs ww3_ounp"
   cdf_programs="$cdf_programs ww3_bounc"
   cdf_programs="$cdf_programs ww3_trnc"
+
+  if [ -n "`grep GLOC $switch_file`" ]
+  then
+    cdf_programs="ww3_grid ww3_strt $cdf_programs"
+  else
+    reg_programs="ww3_grid ww3_strt $reg_programs"
+  fi
 
   # PRTIDE
   if [ -n "`grep TIDE $switch_file`" ]
@@ -204,7 +209,7 @@
   fi
 
   # SHEL PREP GSPL
-  if [ -n "`grep OASIS $switch_file`" ] || [ -n "`grep PDLIB $switch_file`" ]
+  if [ -n "`grep OASIS $switch_file`" ] || [ -n "`grep PDLIB $switch_file`" ] || [ -n "`grep GLOC $switch_file`" ]
   then
     cdf_programs="$cdf_programs ww3_gspl"
     cdf_programs="$cdf_programs ww3_prep"
@@ -213,7 +218,7 @@
     reg_programs="$reg_programs ww3_prep"
   fi
 
-  if [ -n "`grep OASIS $switch_file`" ]  || [ -n "`grep PDLIB $switch_file`" ]
+  if [ -n "`grep OASIS $switch_file`" ]  || [ -n "`grep PDLIB $switch_file`" ] || [ -n "`grep GLOC $switch_file`" ]
   then
     cdf_programs="$cdf_programs ww3_shel"
   else
@@ -236,7 +241,7 @@
 
 # 1.f sort sequential and parallel programs - - - - - - - - - - - - - - - - - -
 
-  # no filtering is done to distinguish sequential to parallel programs 
+  # no filtering is done to distinguish sequential to parallel programs
   # see w3_automake for this feature
   progs=$all_programs
 
@@ -286,7 +291,7 @@
 
 
 
-# 1.c Setup for NetCDF compile - - - - - - - - - - - - - - - - - - - - - - - - 
+# 1.c Setup for NetCDF compile - - - - - - - - - - - - - - - - - - - - - - - -
 
 # 1.c.1 NetCDF compile message function
 
@@ -346,53 +351,53 @@ EOF
   else
     case $WWATCH3_NETCDF in
       NC3)
-        if [ -z "$NETCDF_LIBDIR" ]
-        then
-          netcdf_compile_message
-          echo "$mode: NETCDF_LIBDIR not defined"; echo ' '
-          return 1
-        fi
-        if [ -z "$NETCDF_INCDIR" ]
-        then
-          netcdf_compile_message
-          echo "$mode: NETCDF_INCDIR not defined"; echo ' '
-          return 1
-        fi
+	if [ -z "$NETCDF_LIBDIR" ]
+	then
+	  netcdf_compile_message
+	  echo "$mode: NETCDF_LIBDIR not defined"; echo ' '
+	  return 1
+	fi
+	if [ -z "$NETCDF_INCDIR" ]
+	then
+	  netcdf_compile_message
+	  echo "$mode: NETCDF_INCDIR not defined"; echo ' '
+	  return 1
+	fi
       ;;
       NC4)
-        if [ ! -n "`grep NC4 $switch_file`" ]
-        then
-          echo "WARNING: NC4 is set in WWATCH3_NETCDF but not in the switch file"; echo ' '
+	if [ ! -n "`grep NC4 $switch_file`" ]
+	then
+	  echo "WARNING: NC4 is set in WWATCH3_NETCDF but not in the switch file"; echo ' '
 #          return 1
-        fi
-        if [ -z "$NETCDF_CONFIG" ]
-        then
-          netcdf_compile_message
-          echo "$mode: NETCDF_CONFIG not defined"; echo ' '
-          return 1
-        fi
-        if [ ! -x "$NETCDF_CONFIG" ]
-        then
-          netcdf_compile_message
-          echo "$mode: $NETCDF_CONFIG does not exist or is not executable"; echo ' '
-          return 1
-        fi
-        netcdf_version=`$NETCDF_CONFIG --version | awk '{print $2}'`
-        if [ -z "`echo $netcdf_version | cut -d. -f3`" ]
-        then
-          netcdf_version="$netcdf_version.0"
-        fi
-        if [ `echo $netcdf_version | tr -d .` -lt 411 ]
-        then
-          netcdf_compile_message
-          echo "$mode: NetCDF version $netcdf_version < 4.1.1"; echo ' '
-          return 1
-        fi
+	fi
+	if [ -z "$NETCDF_CONFIG" ]
+	then
+	  netcdf_compile_message
+	  echo "$mode: NETCDF_CONFIG not defined"; echo ' '
+	  return 1
+	fi
+	if [ ! -x "$NETCDF_CONFIG" ]
+	then
+	  netcdf_compile_message
+	  echo "$mode: $NETCDF_CONFIG does not exist or is not executable"; echo ' '
+	  return 1
+	fi
+	netcdf_version=`$NETCDF_CONFIG --version | awk '{print $2}'`
+	if [ -z "`echo $netcdf_version | cut -d. -f3`" ]
+	then
+	  netcdf_version="$netcdf_version.0"
+	fi
+	if [ `echo $netcdf_version | tr -d .` -lt 411 ]
+	then
+	  netcdf_compile_message
+	  echo "$mode: NetCDF version $netcdf_version < 4.1.1"; echo ' '
+	  return 1
+	fi
       ;;
       *)
-        netcdf_compile_message
-        echo "$mode: WWATCH3_NETCDF=$WWATCH3_NETCDF not supported"; echo ' '
-        return 1
+	netcdf_compile_message
+	echo "$mode: WWATCH3_NETCDF=$WWATCH3_NETCDF not supported"; echo ' '
+	return 1
       ;;
     esac
   fi
@@ -410,17 +415,17 @@ EOF
   then
     case $WWATCH3_NETCDF in
       NC3)
-        netcdf_compile_message
-        echo "$mode: WWATCH3_NETCDF=NC3 incompatible with NC4 switch"; echo ' '
-        return 1
+	netcdf_compile_message
+	echo "$mode: WWATCH3_NETCDF=NC3 incompatible with NC4 switch"; echo ' '
+	return 1
       ;;
       NC4)
-        if [ "`$NETCDF_CONFIG --has-nc4`" = 'no' ]
-        then
-          netcdf_compile_message
-          echo "$mode: NetCDF-4 API not enabled (required by NC4 switch)"; echo ' '
-          return 1
-        fi
+	if [ "`$NETCDF_CONFIG --has-nc4`" = 'no' ]
+	then
+	  netcdf_compile_message
+	  echo "$mode: NetCDF-4 API not enabled (required by NC4 switch)"; echo ' '
+	  return 1
+	fi
       ;;
     esac
   fi
@@ -436,11 +441,11 @@ EOF
     then
       echo "NetCDF enabled programs ($cdf_programs)"
       echo "will not be compiled unless NetCDF compile environment is properly set."; echo ' '
-      if [ $systrck_nc4notrknc -eq 1 ] 
-      then 
-         echo "WARNING: ww3_systrk will not be compiled due to invalid switch option."; echo ' '
-         echo "TRKNC switch is also required with NC4."; echo ' '
-      fi 
+      if [ $systrck_nc4notrknc -eq 1 ]
+      then
+	 echo "WARNING: ww3_systrk will not be compiled due to invalid switch option."; echo ' '
+	 echo "TRKNC switch is also required with NC4."; echo ' '
+      fi
       echo "Continuing with compile of non-NetCDF programs ..."; echo ' '
       progs="$reg_programs"
     fi
@@ -450,36 +455,36 @@ EOF
     do
       if [ -n "`echo $progs | grep $prog`" ]
       then
-        nc_compile=1
+	nc_compile=1
       fi
     done
     if [ $nc_compile -eq 1 ]
     then
       if ! netcdf_check_compile ERROR
       then
-        echo "NetCDF enabled programs ($cdf_programs)"
-        echo "will not be compiled unless NetCDF compile environment is properly set."; echo ' '
-        echo "Now exiting ..."; echo ' '
-        exit 1
+	echo "NetCDF enabled programs ($cdf_programs)"
+	echo "will not be compiled unless NetCDF compile environment is properly set."; echo ' '
+	echo "Now exiting ..."; echo ' '
+	exit 1
       fi
     fi
     systrkprog="ww3_systrk"
     for prog in $systrkprog
     do
       if [ -n "`echo $progs | grep $prog`" ]
-      then   
-        if [ $systrck_nc4notrknc -eq 1 ]
-        then
-          echo "ERROR: ww3_systrk will not be compiled due to invalid switch option."; echo ' '
-          echo "TRKNC switch is also required with NC4."; echo ' '
-          echo "Now exiting ..."; echo ' '
-          exit 1
-        fi
+      then
+	if [ $systrck_nc4notrknc -eq 1 ]
+	then
+	  echo "ERROR: ww3_systrk will not be compiled due to invalid switch option."; echo ' '
+	  echo "TRKNC switch is also required with NC4."; echo ' '
+	  echo "Now exiting ..."; echo ' '
+	  exit 1
+	fi
       fi
     done
   fi
 
-# 1.d Prepare scratch directory  - - - - - - - - - - - - - - - - - - - - - - - 
+# 1.d Prepare scratch directory  - - - - - - - - - - - - - - - - - - - - - - -
 
   if test ! -d $temp_dir
   then
@@ -520,23 +525,23 @@ EOF
     then
       if [ "$flag_SHRD" -gt '0' ]
       then
-        if [ "$flag_OMPX" -gt '0' ]
-        then
-          cp $switch_file ${switch_file_old}_OMP
-          cp $makefile ${makefile}_OMP
-        else
-          cp $switch_file ${switch_file_old}_SEQ
-          cp $makefile ${makefile}_SEQ
-        fi
+	if [ "$flag_OMPX" -gt '0' ]
+	then
+	  cp $switch_file ${switch_file_old}_OMP
+	  cp $makefile ${makefile}_OMP
+	else
+	  cp $switch_file ${switch_file_old}_SEQ
+	  cp $makefile ${makefile}_SEQ
+	fi
       else
-        if [ "$flag_OMPH" -gt '0' ]
-        then
-          cp $switch_file ${switch_file_old}_HYB
-          cp $makefile ${makefile}_HYB
-        else
-          cp $switch_file ${switch_file_old}_MPI
-          cp $makefile ${makefile}_MPI
-        fi
+	if [ "$flag_OMPH" -gt '0' ]
+	then
+	  cp $switch_file ${switch_file_old}_HYB
+	  cp $makefile ${makefile}_HYB
+	else
+	  cp $switch_file ${switch_file_old}_MPI
+	  cp $makefile ${makefile}_MPI
+	fi
       fi
     else
       exit 1
@@ -544,7 +549,7 @@ EOF
   fi
   echo ' '
 
-# 1.f Export paths - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
+# 1.f Export paths - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 
   aPb="$main_dir/bin"     # path containing shell scripts
   aPo="$main_dir/obj"     # path containing .o files
@@ -563,14 +568,14 @@ EOF
     echo "Processing $prog"
     echo "---------------------"
 
-# 2.b Check input  - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
+# 2.b Check input  - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 
     OK='n'
     for check in $all_programs
     do
       if test "$prog" = "$check"
       then
-        OK='y'
+	OK='y'
       fi
     done
     if test "$OK" = 'n'
@@ -579,44 +584,44 @@ EOF
       echo ' '
       exit 1
 
-# 2.c Run make - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
+# 2.c Run make - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 
     else
 
       netcdf_compile=no
       if [ -n "`echo $cdf_programs | grep $prog`" ]
       then
-        netcdf_compile=yes
+	netcdf_compile=yes
       fi
       export netcdf_compile
 
       mpi_mod=no
       if [ -n "`grep MPI $switch_file`" ]
       then
-        mpi_mod=yes
+	mpi_mod=yes
       fi
       export mpi_mod
 
       omp_mod=no
       if [ -n "`grep OMP $switch_file`" ]
       then
-        omp_mod=yes
+	omp_mod=yes
       fi
       export omp_mod
 
       oasis_mod=no
-      if [ -n "`grep OASIS $switch_file`" ] 
+      if [ -n "`grep OASIS $switch_file`" ]
       then
-        export oasis_mod='yes'
+	export oasis_mod='yes'
       fi
       export oasis_mod
 
       pdlib_mod=no
-      esmfpdlib='' 
+      esmfpdlib=''
       if [ -n "`grep PDLIB $switch_file`" ]
       then
-        export pdlib_mod='yes'
-        esmfpdlib="$METIS_PATH/lib/libparmetis.a $METIS_PATH/lib/libmetis.a"
+	export pdlib_mod='yes'
+	esmfpdlib="$METIS_PATH/lib/libparmetis.a $METIS_PATH/lib/libmetis.a"
       fi
       export pdlib_mod
 
@@ -627,30 +632,30 @@ EOF
       # processed to get required ESMF compile options
       if [ -n "`echo $prog | grep esmf 2>/dev/null`" ]
       then
-        if [ -z "`grep DIST $switch_file`" ] 
-        then
-          echo ' '
-          echo "*** DIST switch must be set when compiling with ESMF ***"
-          echo ' '
-          exit 1
-        fi
-        ESMF_F90COMPILEPATHS=
-        if [ $ESMFMKFILE ]
-        then
-          if [ ! -r $ESMFMKFILE ]
-          then
-            echo ' '
-            echo "*** ESMFMKFILE does not exist or is not readable: $ESMFMKFILE ***"
-            echo ' '
-            exit 1
-          fi
-          ESMF_F90COMPILEPATHS=`cat $ESMFMKFILE | grep '^ *ESMF_F90COMPILEPATHS' | sed 's/^ *ESMF_F90COMPILEPATHS *=//g'`
-        else
-          echo ' '
-          echo "*** ESMFMKFILE must be defined when compiling with ESMF ***"
-          echo ' '
-          exit 1
-        fi
+	if [ -z "`grep DIST $switch_file`" ]
+	then
+	  echo ' '
+	  echo "*** DIST switch must be set when compiling with ESMF ***"
+	  echo ' '
+	  exit 1
+	fi
+	ESMF_F90COMPILEPATHS=
+	if [ $ESMFMKFILE ]
+	then
+	  if [ ! -r $ESMFMKFILE ]
+	  then
+	    echo ' '
+	    echo "*** ESMFMKFILE does not exist or is not readable: $ESMFMKFILE ***"
+	    echo ' '
+	    exit 1
+	  fi
+	  ESMF_F90COMPILEPATHS=`cat $ESMFMKFILE | grep '^ *ESMF_F90COMPILEPATHS' | sed 's/^ *ESMF_F90COMPILEPATHS *=//g'`
+	else
+	  echo ' '
+	  echo "*** ESMFMKFILE must be defined when compiling with ESMF ***"
+	  echo ' '
+	  exit 1
+	fi
       fi
       export ESMF_F90COMPILEPATHS
 
@@ -658,25 +663,25 @@ EOF
       # the target is compile and create archive
       if [ -n "`echo $prog | grep esmf 2>/dev/null`" ]
       then
-        target="$prog"
+	target="$prog"
       # if program name is libww3, then
       # the target is compile and create archive
       elif [ "$prog" = "libww3" ]
       then
-        target="$prog"
+	target="$prog"
       else
-        target="$aPe/$prog"
+	target="$aPe/$prog"
       fi
 
       if [ ! -f $exec_type_file ] ; then
-          touch $exec_type_file ; fi
+	  touch $exec_type_file ; fi
 
       if [ `grep $prog $exec_type_file | wc -l | awk '{ print $1}'` != '0' ]
       then
-        exec_type=`grep $prog $exec_type_file | tail -1 | awk '{ print $2}'`
+	exec_type=`grep $prog $exec_type_file | tail -1 | awk '{ print $2}'`
       fi
       if [ "$exec_type" != "$pres_type" ] ; then
-          rm -f $main_dir/exe/$prog  ; fi
+	  rm -f $main_dir/exe/$prog  ; fi
 
       cp $exec_type_file tempfile
       sed -n "/$prog/!p" tempfile > $exec_type_file
@@ -688,9 +693,9 @@ EOF
       # it defaults to 4
       if make -j ${WW3_PARCOMPN:-4} -f makefile $target
       then
-        echo ' '
+	echo ' '
       else
-        exit 1
+	exit 1
       fi
 
       echo "$prog $pres_type" >> $exec_type_file
@@ -698,34 +703,34 @@ EOF
       # if esmf is included in program name, then create $main_dir/nuopc.mk
       if [ -n "`echo $prog | grep esmf 2>/dev/null`" ]
       then
-        mkfile=$main_dir/nuopc.mk
-        mod_dir=$main_dir/mod_MPI
-        obj_dir=$main_dir/obj_MPI
-        rm -f $mkfile
-        touch $mkfile
-        echo "#-----------------------------------------------"      >> $mkfile
-        echo "# NUOPC/ESMF self-describing build dependency"         >> $mkfile
-        echo "# makefile fragment for Wavewatch III"                 >> $mkfile
-        echo "#-----------------------------------------------"      >> $mkfile
-        echo "# component module name"                               >> $mkfile
-        echo "ESMF_DEP_FRONT := WMESMFMD"                            >> $mkfile
-        echo "# component module path"                               >> $mkfile
-        echo "ESMF_DEP_INCPATH := $mod_dir"                          >> $mkfile
-        echo "# component module objects"                            >> $mkfile
-        echo "ESMF_DEP_CMPL_OBJS := $obj_dir/lib$prog.a(wmesmfmd.o)" >> $mkfile
-        echo "# component object/archive list"                       >> $mkfile
-        echo "ESMF_DEP_LINK_OBJS := $obj_dir/lib$prog.a $esmfpdlib"  >> $mkfile
+	mkfile=$main_dir/nuopc.mk
+	mod_dir=$main_dir/mod_MPI
+	obj_dir=$main_dir/obj_MPI
+	rm -f $mkfile
+	touch $mkfile
+	echo "#-----------------------------------------------"      >> $mkfile
+	echo "# NUOPC/ESMF self-describing build dependency"         >> $mkfile
+	echo "# makefile fragment for Wavewatch III"                 >> $mkfile
+	echo "#-----------------------------------------------"      >> $mkfile
+	echo "# component module name"                               >> $mkfile
+	echo "ESMF_DEP_FRONT := WMESMFMD"                            >> $mkfile
+	echo "# component module path"                               >> $mkfile
+	echo "ESMF_DEP_INCPATH := $mod_dir"                          >> $mkfile
+	echo "# component module objects"                            >> $mkfile
+	echo "ESMF_DEP_CMPL_OBJS := $obj_dir/lib$prog.a(wmesmfmd.o)" >> $mkfile
+	echo "# component object/archive list"                       >> $mkfile
+	echo "ESMF_DEP_LINK_OBJS := $obj_dir/lib$prog.a $esmfpdlib"  >> $mkfile
       fi
 
     fi
 
   done
 
-# 2.d copy comp and link 
+# 2.d copy comp and link
 
   cp  $main_dir/bin/comp $main_dir/exe/
   cp  $main_dir/bin/link $main_dir/exe/
- 
+
 # --------------------------------------------------------------------------- #
 # 3. End of program ID.                                                       #
 # --------------------------------------------------------------------------- #
